SetPed = function(model)
    local modelHash = GetHashKey(currentModel)
    local health = GetEntityHealth(PlayerPedId())
    SetPedDefaultComponentVariation(PlayerPedId())
    ESX.Streaming.RequestModel(modelHash, function()
        SetPlayerModel(PlayerId(), modelHash)
        SetPedDefaultComponentVariation(PlayerPedId())
        SetModelAsNoLongerNeeded(modelHash)
        SetPedComponentVariation(PlayerPedId(), 8, 0, 0, 2)
        SetPedComponentVariation(PlayerPedId(), 2, 0, 0, 2)
        SetEntityMaxHealth(PlayerPedId(), 200)
        SetEntityHealth(PlayerPedId(), health)
    end)
    Wait(500)
    restoreWeapons()
end